#!/bin/bash

if [ $# -ne 1 ]; then
	echo ERROR
	exit 1
fi

for line in $(cat $1); do
	tmppass=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo)

	echo creating user $line
	useradd $line -p $tmppass
	echo $line created with pwd : $tmppass
done;
